### ISSUE TITLE
Error: No module named spacy

### ISSUE THREAD

**Issue by therohitdas** [fabriceyhc/emoji-translate#1]
Hi @fabriceyhc,
First of all, thank you for creating this project, I really appreciate it.

When I first installed emoji_translate and tried running the sample code, it threw some error -

```bash
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    emo = Translator(exact_match_only=False, randomize=True)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/emoji_translate/emoji_translate.py", line 17, in __init__
    from spacy.lang.en.stop_words import STOP_WORDS
ModuleNotFoundError: No module named 'spacy'
```
Fix was to install spacy separately.

**Comment by 2br-2b** [comment]
I had the same problem, but I also had to install `regex` first
